#!/bin/sh

function archive(){
	archiveDir=$(echo f:/archive/$(date "+%Y%m%d") )
	ztemp=$archiveDir/temp
	loginfo=$ztemp/loginfo
	sourcelist=$ztemp/sourcelist
	msourcelist=$ztemp/msourcelist
	destlist=$archiveDir/dest
	dest=$destlist 
	updatelist=./updatelist
	currentdirupdatelist=$archiveDir/updatelist

	if [ ! -d $archiveDir ]
	then
		mkdir -p $archiveDir
	fi

	if [ ! -d $archiveDir/temp ]
	then
		mkdir -p $archiveDir/temp
	fi
	
	git log HEAD@{${1:-0}} -1 --name-status --pretty=format:"%ad" --date=format:"%Y%m%d%H%M$S" > $loginfo

	modifieddate=$archiveDir/$(sed -n "1p" $loginfo)
	 awk '$2~/^WebRoot/ ' $loginfo > $sourcelist 
	sed -n '/^A/p' $sourcelist > $updatelist 
	echo "                                                      " >> $updatelist
	echo "                                                      " >> $updatelist
	echo "                                                      " >> $updatelist
	echo "                                                      " >> $updatelist
	sed  -n '/^M/p' $sourcelist >>$updatelist 
	echo "                                                      " >> $updatelist
	echo "                                                      " >> $updatelist
	echo "                                                      " >> $updatelist
	echo "                                                      " >> $updatelist
	sed -n  '/^D/p' $sourcelist >> $updatelist
	cp $updatelist $currentdirupdatelist
	awk '$1~/^[AM]/ {print $2}' $updatelist > $msourcelist
	c=$(awk 'END{print FNR;}' $msourcelist)
	basecount=50
	if [ -f $modifieddate.zip ]
	then
		rm -rf $modifieddate.zip
	fi
	
	for (( i=0; i <= ((c/basecount)); i++ ))
	do
		beginline=$((i*basecount+1))
		endline=$((beginline+basecount-1))
		zip $modifieddate.zip $(eval sed -n \'$beginline,${endline}p\' $msourcelist ) $updatelist 	
	done
	if [ -f $dest.zip ]
	then
		rm -rf $dest.zip
	fi
	cp $modifieddate.zip  $dest.zip
	trap "rm -rf $updatelist $ztemp/ " EXIT
}


archive $@
function backup(){
	updatlist=$1
	
	
	
}

function updateopt(){
	sourcedir="F:/archive/20170430/"
	destdir="E:/apache-tomcat-7.0.57/jxhbwf/"
	sourcedir=$sourcedir "dest.zip"
	unzip $sourcedir -d .
	
	
}

